# Generated by Django 3.1.7 on 2021-05-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignments',
            name='assignment',
            field=models.TextField(null=True),
        ),
    ]
