# Generated by Django 3.1.7 on 2021-05-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20210514_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignments',
            name='assignment',
            field=models.TextField(),
        ),
    ]
