# Generated by Django 3.1.7 on 2021-05-14 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_studentassignments_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignments',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.courses'),
            preserve_default=False,
        ),
    ]
