# Generated by Django 3.1.7 on 2021-05-05 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_studentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='session_year_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.sessionyearmodel'),
            preserve_default=False,
        ),
    ]
