# Generated by Django 3.1.7 on 2021-05-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_studentresult_session_year_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='session_year_id',
        ),
    ]
