# Generated by Django 3.1.7 on 2021-05-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_remove_studentresult_session_year_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionyearmodel',
            name='session_term',
            field=models.CharField(default='1st Term', max_length=50),
            preserve_default=False,
        ),
    ]
