# Generated by Django 3.2.5 on 2021-07-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_sessionyearmodel_session_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionyearmodel',
            name='session_term',
            field=models.CharField(max_length=50),
        ),
    ]
