# Generated by Django 3.1.7 on 2021-05-11 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_sessionyearmodel_session_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='session_year_id',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='management.sessionyearmodel'),
            preserve_default=False,
        ),
    ]
