# Generated by Django 3.1.7 on 2021-05-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_studentresult_class_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionyearmodel',
            name='session_year_session',
            field=models.CharField(default='2021/2022', max_length=50),
            preserve_default=False,
        ),
    ]
